### ISSUE TITLE
Enter integer value for port number message

### ISSUE THREAD

**Issue by MajdiZ** [yashbathia/freeport#3]
When I try freeport 3000
I get a message `Enter integer value for the port number`
but if I try When I try freeport 8000
I get `No process running on port 8000`

**Comment by vincentclaes** [comment]
@yashbathia i have the same when i try to do freeport 8080

**Comment by laurafitzgerald** [comment]
I'm also getting `Enter integer value for port number` when running `freeport 8443`

**Comment by ghost** [comment]
same here 8080. Has anyone resolved this?

**Comment by SirPhemmiey** [comment]
I had to uninstall this library because of the issues i was facing in running it. 

Just in case anyone needs a simple command to free a port, you can use the following code

```
import subprocess
subprocess.run('kill $(lsof -t -i :<portnumber>)', shell=True)
```

**Comment by yashbathia** [comment]
Issue should be fixed by above commit
