### ISSUE TITLE
Getting `invalid literal for int() with base 10`

### ISSUE THREAD

**Issue by deutranium** [yashbathia/freeport#8]
Hi I'm trying to use freeport as follows:
```
freeport 3000   
```
but it's giving me
``` 
invalid literal for int() with base 10: b'764\n40841\n'
```

any help in what could've been wrong is highly appreciated

**Comment by yashbathia** [comment]
@deutranium  Which version of freeport are you using?  Can you try using the latest release?

pip install freeport==0.1.14

**Comment by deutranium** [comment]
Hi @yashbathia 
I'm using 0.1.14 only with Python 3.8. Not sure why the error is there

**Comment by yashbathia** [comment]
@deutranium pushed freeport-0.1.15 which should address this issue. Can you please install latest version and let me know if it helped?

pip install freeport==0.1.15

**Comment by deutranium** [comment]
Yupp @yashbathia it works now!
